Fixed template text for teams page goal section
gdg-galway/gdg-galway pull request #18
Opened 2019-10-14 16:17 UTC by shadab

2019-10-14 16:20 UTC, Omnighost547 commented on src/views/Team.vue
> +          >Our goal is to build a community of developers who are interested in development technologies including but not lmited to google products. Our Core Team is:</p>
```suggestion
          >Our goal is to build a community of developers who are interested in development technologies including but not limited to Google products. Our Core Team is:</p>
```

2019-10-14 16:22 UTC, tombolide requested changes
Formatting - see suggestion.

2019-10-14 16:22 UTC, Omnighost547 commented on src/views/Team.vue
> +          >Our goal is to build a community of developers who are interested in development technologies including but not lmited to google products. Our Core Team is:</p>
```suggestion
          >Our goal is to build a community of developers who are interested in development technologies including but not limited to Google products. Our Core Team is:</p>
```

2019-10-15 14:44 UTC, rossanodan approved these changes
Good one guys! 👍

2019-10-15 14:44 UTC, merged